---
title: "MTH440 Presentation
        Jacob Baiardi and Kate Ferland"
output: ioslides_presentation
date: "2025-04-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## 3D Plots of every reported instance of a school's average teacher salary, teacher retention rate, and graduation rate by year

## 0 - 100 % Graduation Rate

```{r load-packages, include=FALSE}
library(readr); library(dplyr);library(ggplot2);library(scatterplot3d);library(rgl)
```

```{r}
z_Salary_Total = read.csv("SalariesTotals.csv")
z_Grad_Total = read.csv('GraduationTotal.csv')
z_Reten_Total = read.csv('RetentionTotal.csv')
z_Reten_Total = z_Reten_Total[-c(2797,2973,3085,3204,3377,3488,3782,4029,4912,5714, 5701,5856, 392, 778, 1949, 2351, 2753, 3159, 3564, 3970, 4375, 4780, 5182, 5584, 5984, 1161, 1552),]
z_Grad_select = subset(z_Grad_Total, select = c('District.Code', 'Percent_Graduated', 'Year'))
z_Salary_select = subset(z_Salary_Total, select = c('District.Code', 'AverageSalaryInDollars', 'Year'))
z_Reten_select = subset(z_Reten_Total, select = c('District.Code', 'Teacher...Retained.1', 'Year'))
z_Reten_select = rename(z_Reten_select, 'Teacher.Retention' = 'Teacher...Retained.1')
Salary_Grad_Merged = merge(z_Grad_select, z_Salary_select)
Salary_Reten_Grad_Merged = merge(Salary_Grad_Merged, z_Reten_select)
a80percentGrad = filter(Salary_Reten_Grad_Merged, Percent_Graduated > 80)
a90percentGrad = filter(Salary_Reten_Grad_Merged, Percent_Graduated > 90)
a95percentGrad = filter(Salary_Reten_Grad_Merged, Percent_Graduated > 95)
 
plot3d(x=Salary_Reten_Grad_Merged$AverageSalaryInDollars, y=Salary_Reten_Grad_Merged$Teacher.Retention, z=Salary_Reten_Grad_Merged$Percent_Graduated,
       type="s", size=1,
       xlab = "Average Teacher Salary ($)", ylab= "Teacher Retention Rate", zlab= "Graduation Rate")
rglwidget(elementId = "nmds")

```

## 80% ≤ Graduation Rate

```{r}
plot3d(x=a80percentGrad$AverageSalaryInDollars, y=a80percentGrad$Teacher.Retention, z=a80percentGrad$Percent_Graduated,
       type="s", size=1,
       xlab = "Average Teacher Salary ($)", ylab= "Teacher Retention Rate", zlab= "Graduation Rate")
rglwidget(elementId = "nmd")
```

## 90% ≤ Graduation Rate
```{r}
plot3d(x=a90percentGrad$AverageSalaryInDollars, y=a90percentGrad$Teacher.Retention, z=a90percentGrad$Percent_Graduated,
       type="s", size=1,
       xlab = "Average Teacher Salary ($)", ylab= "Teacher Retention Rate", zlab= "Graduation Rate")
rglwidget(elementId = "nm")
```

## 95% ≤ Graduation Rate
```{r}
plot3d(x=a95percentGrad$AverageSalaryInDollars, y=a95percentGrad$Teacher.Retention, z=a95percentGrad$Percent_Graduated,
       type="s", size=1,
       xlab = "Average Teacher Salary ($)", ylab= "Teacher Retention Rate", zlab= "Graduation Rate")
rglwidget(elementId = "n")
```



